// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1pCVGOCO-51D2pa7WIAZsdLauEJg1LnI',
    appId: '1:2119481677:web:8b2b1c58a8f2c0dc201f04',
    messagingSenderId: '2119481677',
    projectId: 'onboaring-app',
    authDomain: 'onboaring-app.firebaseapp.com',
    storageBucket: 'onboaring-app.appspot.com',
    measurementId: 'G-8DFGN6ZE9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjDSH90YvFfwkyXCvhtaP5XoO8jAiLCg',
    appId: '1:2119481677:android:4339d38faa4d2d2e201f04',
    messagingSenderId: '2119481677',
    projectId: 'onboaring-app',
    storageBucket: 'onboaring-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCszUC7JbBMdZdIm8UqWwHCRmKL7ahv1KU',
    appId: '1:2119481677:ios:5eb09546ed82043d201f04',
    messagingSenderId: '2119481677',
    projectId: 'onboaring-app',
    storageBucket: 'onboaring-app.appspot.com',
    iosClientId: '2119481677-f1egf5805c0thpgf9g1odu4gk1hkgkns.apps.googleusercontent.com',
    iosBundleId: 'com.example.customerOnboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCszUC7JbBMdZdIm8UqWwHCRmKL7ahv1KU',
    appId: '1:2119481677:ios:5eb09546ed82043d201f04',
    messagingSenderId: '2119481677',
    projectId: 'onboaring-app',
    storageBucket: 'onboaring-app.appspot.com',
    iosClientId: '2119481677-f1egf5805c0thpgf9g1odu4gk1hkgkns.apps.googleusercontent.com',
    iosBundleId: 'com.example.customerOnboard',
  );
}
